apiVersion: 1

datasources:
  - name: Prometheus HX141 Real
    uid: PROMETHEUS_REAL
    type: prometheus
    access: proxy
    url: http://prometheus-real:9090
    isDefault: true
    editable: true
