global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "genieacs-qoe-exporter-real-hx141"
    static_configs:
      - targets:
          - "genieacs-qoe-exporter:9108"

  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"